spring:
  application:
    name: order-processing-system

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:order_processing_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:15421542}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-processing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${SERVER_PORT:8080}

app:
  product-catalog:
    url: ${PRODUCT_CATALOG_URL:http://localhost:8081}
  order:
    alert-stock-low: 5
    high-value-threshold: 10000
    fraud-check-threshold: 20000
    subscription-limit: 5
    stock-zero: 0
    corporate-approval-threshold: 50000
    corporate-volume-discount-threshold: 100
    topic:
      created: order-events-created
      processed: order-events-processed
      failed: order-events-failed
      low-stock: order-events-low-stock
      fraud-alert: order-events-fraud-alert
      scheguling-payment: order-events-scheguling-payment

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.ecommerce: DEBUG
    org.apache.kafka.clients.producer: WARN
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka: WARN
